# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20161127_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='messaging.Message'),
        ),
    ]
