# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20161127_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=20),
        ),
    ]
